# Generated by Django 6.0.5 on 2026-05-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageInstitutionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_page', models.CharField(choices=[('PRESENTATION', 'Présentation & Missions'), ('HISTORIQUE', 'Historique'), ('EQUIPE', 'Équipe Dirigeante')], max_length=20, unique=True, verbose_name='Page cible')),
                ('titre_principal', models.CharField(max_length=200, verbose_name='Grand Titre de la Page')),
                ('sous_titre', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sous-titre / Accroche')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name="Texte d'introduction")),
                ('contenu_principal', models.TextField(help_text='Vous pouvez utiliser du texte ou du HTML basique', verbose_name='Corps du texte / Contenu principal')),
                ('bloc_secondaire', models.TextField(blank=True, null=True, verbose_name="Bloc d'information complémentaire")),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Institutionnelle',
                'verbose_name_plural': 'Pages Institutionnelles',
            },
        ),
    ]
