# Generated by Django 6.0.5 on 2026-05-28 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('description', models.CharField(max_length=250, verbose_name='Description rapide')),
                ('icone', models.CharField(default='fas fa-comments', help_text='Classe FontAwesome (ex: fas fa-graduation-cap)', max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie Forum',
                'verbose_name_plural': 'Catégories Forum',
            },
        ),
        migrations.CreateModel(
            name='SujetForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du sujet')),
                ('message_origine', models.TextField(verbose_name='Message initial')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_epinglé', models.BooleanField(default=False, verbose_name='Épingler en haut')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to='forum.categorieforum')),
            ],
            options={
                'verbose_name': 'Sujet de discussion',
                'verbose_name_plural': 'Sujets de discussion',
                'ordering': ['-est_epinglé', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Votre réponse')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_forum', to=settings.AUTH_USER_MODEL)),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='forum.sujetforum')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'ordering': ['date_publication'],
            },
        ),
    ]
