# Generated by Django 6.0.5 on 2026-06-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_emploidutemps_enseignant'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2')], max_length=20, null=True, verbose_name="Niveau d'études (Étudiants)"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='academics.filiere', verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role_user',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('ENSEIGNANT', 'Enseignant'), ('ETUDIANT', 'Étudiant'), ('ALUMNI', 'Alumni')], default='ETUDIANT', max_length=20, verbose_name='Rôle'),
        ),
    ]
