# Generated by Django 6.0.5 on 2026-05-12 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ACAD', 'Académique'), ('ADMIN', 'Administratif'), ('EVENT', 'Événement')], default='EVENT', max_length=5)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='announcements/docs/')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
