# Generated by Django 6.0.5 on 2026-05-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Département')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom de la filière')),
                ('acronym', models.CharField(max_length=10, verbose_name='Sigle (ex: MIAGE)')),
                ('degree_level', models.CharField(choices=[('Licence', 'Licence Professionnelle'), ('Master', 'Master Professionnel')], default='Licence', max_length=20)),
                ('description', models.TextField(verbose_name='Présentation')),
                ('admission_criteria', models.TextField(verbose_name="Conditions d'admission")),
                ('opportunities', models.TextField(verbose_name='Débouchés')),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='academics.department')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
    ]
