# Generated by Django 6.0.5 on 2026-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_filiere', models.AutoField(primary_key=True, serialize=False)),
                ('nom_filiere', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duree', models.CharField(max_length=50)),
                ('condition_acces', models.TextField()),
                ('debouches', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='formation',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
    ]
