# Generated by Django 6.0.5 on 2026-05-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_emploidutemps'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='semaine_du',
            field=models.CharField(default='Semaine en cours', help_text='Ex: Du 25 au 30 mai 2026', max_length=100, verbose_name='Période / Semaine'),
        ),
    ]
