# Generated by Django 6.0.5 on 2026-05-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_emploidutemps_semaine_du'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='niveau_etude',
            field=models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2')], default='Licence 1', max_length=20, verbose_name="Niveau d'études"),
        ),
    ]
