# Generated by Django 6.0.5 on 2026-06-05 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_emploidutemps_niveau_etude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10, verbose_name='Jour proposé')),
                ('periode', models.CharField(choices=[('MATIN', 'Matin (07h00 - 12h00)'), ('APRES_MIDI', 'Après-midi (13h00 - 18h00)'), ('JOURNEE', 'Journée complète')], max_length=15, verbose_name='Créneau horaire')),
                ('note_complementaire', models.TextField(blank=True, help_text='Ex: Seulement libre à partir de 15h00 ce jour-là.', null=True, verbose_name='Précisions ou contraintes particulières')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites_soumises', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Disponibilité Enseignant',
                'verbose_name_plural': 'Disponibilités Enseignants',
                'ordering': ['jour'],
            },
        ),
        migrations.CreateModel(
            name='RessourcePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_etude', models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2')], max_length=20, verbose_name="Niveau d'études ciblé")),
                ('titre_cours', models.CharField(max_length=150, verbose_name='Titre du support de cours')),
                ('fichier', models.FileField(upload_to='cours_supports/', verbose_name='Fichier du cours (PDF, Word, etc.)')),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_deposees', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_pedagogiques', to='academics.filiere', verbose_name='Filière ciblée')),
            ],
            options={
                'verbose_name': 'Ressource Pédagogique',
                'verbose_name_plural': 'Ressources Pédagogiques',
                'ordering': ['-date_depot'],
            },
        ),
    ]
