# Generated by Django 6.0.5 on 2026-06-06 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_disponibiliteenseignant_ressourcepedagogique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploidutemps',
            name='enseignant',
            field=models.ForeignKey(limit_choices_to={'role_user': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='cours_planifies', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant'),
        ),
    ]
